### ISSUE TITLE
Add Installer

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [meltmedia/rodimus#18]
Make this so a developer can get it running without any help. A really simple installer or very detailed documentation will close this issue.

**Comment by 10xLaCroixDrinker** [comment]
Consider using hombrew

http://mxcl.github.com/homebrew/

**Comment by ctrimble** [comment]
Rodimus is now installable using homebrew.  I added a tap for meltmedia to github, so you will need to install that tap and then install rodimus.  Since we do not have an official release, the current formula only defines a head version.

``` bash
brew tap meltmedia/homebrew-meltmedia
brew install --HEAD rodimus
```
