### ISSUE TITLE
References text left out of conversion

### ISSUE THREAD

**Issue by jleemccaslin** [meltmedia/rodimus#24]
In the most recent conversion I did, the references at the bottom of the page were stripped out of the final HTML doc. I can provide the .docx where the problem occurred.

**Comment by 10xLaCroixDrinker** [comment]
Please, email me a copy of the document.

**Comment by 10xLaCroixDrinker** [comment]
This sounds like it's related to issue #11 (possibly also #25 )

**Comment by 10xLaCroixDrinker** [comment]
This duplicates #11
