### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [meltmedia/rodimus#3]
Output should be properly serialized HTML with space between block elements, inline elements staying in line and space before the end of a self-closing tag.

**Comment by ctrimble** [comment]
I modified the code to correct `/>` to `/>` for self closing tags.  Some hacking on the serializer will be required to fix the block and inline elements properly, since indent levels will also be involved in that.

**Comment by ctrimble** [comment]
The serializer has been configured to render the document as though it is US-ASCII, even though it reports to be UTF-8.  This improvement completes the general serialization problems we were having.
