### ISSUE TITLE
Build as a web app

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [meltmedia/rodimus#7]

**Comment by 10xLaCroixDrinker** [comment]
@ctrimble I'm going to build this in node. Do you want this in a [web-app] branch or a separate repo?

**Comment by ctrimble** [comment]
It would be good to keep it all together.  I would just create a bare branch.

**Comment by 10xLaCroixDrinker** [comment]
https://jira.meltdev.com/browse/ITCORE-86
